import { describe, it } from '@std/testing/bdd';
import { expect } from '@std/expect';
import { part1, part2 } from './day7.ts';

const input = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

describe('day 7, part 1', () => {
  it('should work with test input', () => {
    expect(part1(input)).toBe(21);
  });
});

describe('day 7, part 2', () => {
  it('should work with test input', () => {
    expect(part2(input)).toBe(40);
  });
});
